# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
# data:
#   # property-like keys; each key maps to a simple value
#   postgres_password: secretpassword
#   postgres_user : postgres
