apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: default
spec:
  encryptedData:
    postgres-password: AgA+OEHp+IicC+WlM/Puqw0m72bDnRu+3PEmw4WtDj9esftTL5/OAWrBOtgd5LBGGG2PVYKGQzf+w92ifgCvHZrOnWSKRq6gnkGBT43R+6D/hOO14P4/6tuBA4BRMgXgPi04k6jLBcFxZp9l5mLXM25T8fwBQzVKJNXj5N7SRKgrk9EW/wsD9/TpMuF3cQWGX9ypHsyNsCxgjKdPeVQ00MBVQe54LZSbrkdJj/gQLfXUgyl8qUnckmF81/MeMrYE3gPP2uEziN/5rBFvTdjaj1IOkjBFXmUyGZ1tSKJWs+wFi0t/uBJRvlSV+N4Tkpd2EKkBZXTlJ8fYkRzdt7jVQVy41Tm3dw2cee+rvP5RRwgBo9M+Y3Hz2NjFRzUyvxxU8qIM3yiq73tdzvivCXj16XOSSVZmxZmw2pxgQRex+jeyJUEQWzK4u7zrQqYh8zr2E3a6PdHDAyJFQdeohSPpGSPkWpLx5R07/sgot7bX/sjvXC0Vj1IHX+DBs+uTd0gCjU1oHzIKF5vt/kM3ilxgylipyWlIXwxFYP02kqbfYROV387HBu6qmlOnWpPZ7CiSg58hIkhGor1agED1RacfUw2ODo8EjI15Wymyd2e7FzkjIbUlEysdC/ykTeaInukLBYsrfOGxyv9Mk63RLJOFm1D+tRyHdXQAtTHVCVxBOPBgo05omhhs0Xvyz77DqpHHTlMiNg3D8AL5r8Y6XBCOLg==
    postgres-user: AgCk/tgWocKenUkIWaxevK+K1MBYhHjxujD3FvB5Zjbqktxnc7zPp5MqOZHhM1lV6qiAMVqLyVJuDijb44itfHgZ1N6VFxwhOlzeQVUOTDSvX1Rr0hjIVB1zb9dbP/fnIQuqOreqdREKXsEXHQ9rN652O7AcURK2yKLoJGaeQfzWYC1JrQi/93oHg0XMvyoyADqN8P1lL4QncRYBNFayeTugCRbRIzqUTQvfK7HqUhtIoj7xJz0lPKUlCmZvVpxWQShMgeUtj0NDv353eZwdqhbyF+Il0zA7etPjr5fbdTF3pQK37sW3ut4taEJSGoCHpj1P+iCHKpyGXx2sJmkdi/7kc+4mUJYhcgoctWztKurcrJ7yHjHx4eQn8IedTX5Cq+R4dYxYVrlQMB/vKKsGKZbIcBkWYk3qmz7aAGMegNEStyKEtIURdnJ+/G/w/NZ6CNlHJqoWOUfGTlXyoKQZTPvWxEkKlAffwWzQJ4wVEyrdbR3t3Ejiz9EP1vA3biRcRGFy/IeUCUvadjFg6Egxg8LbkNh6iJqNVC/RtznGt8z3xwb+SSHELP3Nxx74xAhIktAG8E4/44EklOuzzOcrsQ3HxnINbAT5tRoNePM+Yi8N1C4/ErTslq3W8NA/N5Zpr0WX8x2rOHEEHrWISvwjo7nQVUqoVAKWMJ+F5C0rAquAFSwl2FNo/CI5OHpmKpEK+anjyOOctpD4tA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: default

