apiVersion: v1
kind: Service
metadata:
  name: mainapp-svc
spec:
  type: ClusterIP
  selector:
    app: main-pingpong
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
