apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgen
  template:
    metadata:
      labels:
        app: hashgen
    spec:
      containers:
        - name: hashgen
          image: jhiekkap/mainapp