apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-pingpong
  template:
    metadata:
      labels:
        app: main-pingpong
    spec:
      volumes:
        - name: shared-pingpong
          persistentVolumeClaim:
              claimName: pingpong-claim
      containers:
        - name: mainapp
          image: jhiekkap/mainapp:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-pingpong
              mountPath: /mydir/files
        - name: pingpong
          image: jhiekkap/pingpong:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-pingpong
              mountPath: /mydir/files
