apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mp-claim
  namespace: mp
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
